config/routes.rb
Depstack::Application.routes.draw do
  match '/vote/:id' => 'votes#toggle', as: :vote, via: [:post, :get]
  get '/votes' => 'votes#show', as: :votes
  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", as: :signout
  get '/libraries/:manager/:name' => 'libraries#show', as: :library, constraints: { name: /.+/ }
  get '/popular/:manager' => 'libraries#index', as: :popular
  get '/graph/:manager' => 'libraries#graph', as: :graph
  root "welcome#new"
end

app/models/library.rb
require 'open-uri'

class Library < ActiveRecord::Base
  include AlgoliaSearch
  algoliasearch per_environment: true, auto_index: false, auto_remove: false do
    add_attribute :short_name do
      case manager_cd
      when Library.composer
        p = name.split('/')
        (p.length >= 2 ? p[1..-1] : p).join('/')
      when Library.go
        p = name.split('/')
        (p.length >= 3 ? p[2..-1] : p).join('/')
      else
        name
      end
    end
    attribute :name, :description, :downloads, :manager, :language, :homepage_uri, :repository_uri, :score, :votes_count
    add_attribute :used_by do
      used_by.uniq(&:name).sort { |a,b| b.votes_count <=> a.votes_count }.first(5).map(&:name)
    end
    add_attribute :used_by_count do
      used_by.size
    end
    attributesForFaceting [:language]
    tags do
      [manager.to_s]
    end
    attributesToIndex ['unordered(short_name)', 'unordered(description)', :language, 'unordered(homepage_uri)', 'unordered(repository_uri)']
    customRanking ['desc(score)', 'desc(used_by_count)']
  end

  has_many :dependencies, foreign_key: 'source_id', dependent: :destroy
  has_many :using, through: :dependencies, source: :destination

  has_many :requirements, class_name: 'Dependency', foreign_key: 'destination_id', dependent: :destroy
  has_many :used_by, through: :requirements, source: :source

  has_many :votes, dependent: :destroy
  has_many :users, through: :votes

  as_enum :manager, [:rubygems, :npm, :bower, :composer, :pip, :go, :julia, :apm, :bower]

  def score
    used_by.inject(votes_count) { |sum, lib| sum + lib.votes_count }
  end

  def language
    case platform
    when "ruby", "jruby"
      'Ruby'
    when 'go'
      'Go'
    when 'python'
      'Python'
    when 'php'
      'PHP'
    when 'js'
      'JavaScript'
    when 'node'
      'Node.js'
    when 'java'
      'Java'
    when 'julia'
      'Julia'
    when 'atom'
      'Atom'
    else
      nil
    end
  end

  def top_requirements(limit)
    requirements.joins(:source).select('dependencies.*, libraries.votes_count AS votes_count').order('votes_count DESC').first(limit)
  end

  def github?
    uri = repository_uri || homepage_uri
    uri && uri['github.com']
  end

  def github_repository
    return nil if !github?
    (repository_uri || homepage_uri).scan(/github\.com\/([^\/]+)\/([^\/]+)/).first
  end

  def self.load!(manager, name, fast = false)
    manager_cd = Library.managers[manager.to_s]
    library = Library.find_or_initialize_by(manager_cd: manager_cd, name: name)
    return library if !library.new_record? && fast
    case manager_cd
    when Library.rubygems
      json = JSON.parse(open("http://rubygems.org/api/v1/gems/#{name}.json").read) rescue nil
      if json
        library.downloads = json['downloads']
        library.platform = json['platform']
        library.description = json['info']
        library.homepage_uri = json['homepage_uri']
        library.repository_uri = json['source_code_uri']
        library.load_dependencies! (json['dependencies']['development'] or []).map { |r| { name: r['name'], requirement: r['requirements'], environment: :development } } +
          (json['dependencies']['runtime'] or []).map { |r| { name: r['name'], requirement: r['requirements'], environment: :runtime } }
      end
    when Library.npm, Library.bower
      json = JSON.parse(open("https://registry.npmjs.org/#{name}").read) rescue nil
      if json
        library.downloads = 0
        library.platform = (json['versions'] || {}).detect { |version,spec| (spec['engines'] || {}).detect { |k,v| k['node'] } } ? 'node' : 'js' rescue 'js'
        library.description = json['description']
        library.homepage_uri = json['homepage'].is_a?(Array) ? json['homepage'].first : json['homepage']
        library.repository_uri = json['repository'] && (json['repository'].is_a?(Array) ? json['repository'].first : json['repository'])['url']
        last_version = json['dist-tags']['latest'] rescue nil
        last_version ||= json['versions'].try(:first).try(:first)
        if last_version
          devDependencies = (json['versions'][last_version] || json['versions'].first || {})['devDependencies'] rescue nil
          dependencies = (json['versions'][last_version] || json['versions'].first || {})['dependencies'] rescue nil
          library.load_dependencies! (devDependencies || {}).map { |k, v| { name: k, requirement: v, environment: :development } } + 
            (dependencies || {}).map { |k, v| { name: k, requirement: v, environment: :runtime } }
        end
      end
    when Library.composer
      json = JSON.parse(open("https://packagist.org/packages/#{name}.json").read) rescue nil
      if json
        library.downloads = json['package']['downloads'] && json['package']['downloads']['total']
        library.platform = 'php'
        library.description = json['package']['description']
        library.homepage_uri = nil
        library.repository_uri = json['package']['repository']
        version = (json['package']['versions']['dev-master'] || json['package']['versions'].first.last) rescue {}
        library.load_dependencies! (version['require'] || []).map { |k, v| { name: k, requirement: v, environment: :runtime } } +
          (version['require-dev'] || []).map { |k, v| { name: k, requirement: v, environment: :runtime } }
      end
    when Library.pip
      json = JSON.parse(open("https://pypi.python.org/pypi/#{name}/json").read) rescue nil
      if json
        library.downloads = json['info']['downloads']['last_month']
        library.platform = 'python'
        library.description = json['info']['summary']
        library.homepage_uri = json['info']['home_page']
        library.repository_uri = json['info']['project_url']
        if library.repository_uri.is_a?(Array)
          library.repository_uri = (library.repository_uri.first || '').split(',').last
        end
        # TODO: The metadata available for packages on PyPI does not include
        #       information about the dependencies.
        # library.load_dependencies!
      end
    when Library.go
      json = JSON.parse(open("http://go-search.org/api?action=package&id=#{CGI.escape name}").read) rescue nil
      if json
        library.downloads = json['StarCount']
        library.platform = 'go'
        library.description = json['Synopsis']
        library.description = json['Description'] if library.description.blank?
        library.homepage_uri = json['ProjectURL']
        library.load_dependencies! (json['Imports'] || []).map { |v| { name: v } }
      end
    when Library.apm
      json = JSON.parse(open("https://atom.io/api/packages/#{CGI.escape name}").read) rescue nil
      if json
        library.downloads = 0
        library.platform = 'atom'
        if json['metadata']
          library.description = json['metadata']['description']
          repository = json['metadata']['repository'] && (json['metadata']['repository'].is_a?(Array) ? json['metadata']['repository'].first : json['metadata']['repository'])
          library.repository_uri = repository.is_a?(Hash) ? repository['url'] : repository
          deps = (json['metadata']['dependencies'] || []).map do |k, v|
            apm_package = open("https://atom.io/api/packages/#{CGI.escape k}").read rescue false
            { name: k, requirement: v, manager: (apm_package ? :apm : :npm) }
          end
          library.load_dependencies! deps
        end
        library.repository_uri ||= json['repository']['url'] if json['repository']
      end
    else
      raise "Unknown manager: #{manager}"
    end
    library.save!
    library
  end

  def load_dependencies!(deps)
    save!
    self.dependencies = deps.map do |dep|
      manager = dep[:manager] || self.manager
      library = Library.load!(manager, dep[:name], true)
      requirement = dep[:requirement]
      requirement = requirement['version'] if requirement.is_a?(Hash)
      Dependency.new(source_id: id, destination_id: library.id, environment: dep[:environment], requirement: requirement)
    end
    save!
  end

end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  def show
    manager_cd = Library.managers(params[:manager].to_s)
    raise ActiveRecord::RecordNotFound.new("Manager not found") if manager_cd.nil?
    @library = Library.find_by!(manager_cd: manager_cd, name: params[:name])
  end

  def index
    @manager = params[:manager]
  end

  def graph
    @manager = params[:manager]
    manager_cd = Library.managers(params[:manager].to_s)
    raise ActiveRecord::RecordNotFound.new("Manager not found") if manager_cd.nil?
    if request.format.json?
      @libraries = Library.where(manager_cd: manager_cd).order(votes_count: :desc).includes(:dependencies).limit(100)
      nodes = []
      @libraries.each do |lib|
        ([lib] + lib.using).each do |d|
          nodes << { name: d.name }
        end
      end
      nodes.uniq!
      links = []
      @libraries.each do |lib|
        lib.dependencies.each do |dep|
          source_idx = nodes.find_index(name: dep.source.name)
          destination_idx = nodes.find_index(name: dep.destination.name)
          next if source_idx.nil? || destination_idx.nil?
          links << {
            source: source_idx,
            target: destination_idx,
            value: [dep.requirement, dep.environment].join(' ')
          }
        end
      end
      render json: { nodes: nodes, links: links }
      return
    end
  end
end

app/helpers/libraries_helper.rb
require 'github/markup'
require 'open-uri'

module LibrariesHelper

  def render_readme(user, name)
    %w{README.md README.markdown README.textile README.rdoc Readme.md Readme.markdown Readme.textile Readme.rdoc README.rst Readme.rst README}.each do |f|
      content = open("https://raw.github.com/#{user}/#{name}/HEAD/#{f}").read rescue nil
      next if content.blank?
      code = GitHub::Markup.render(f, content).gsub(/(?!<pre>)<code>(.*?)<\/code>/m) do |match|
        match["\n"] ? "<pre>#{match}</pre>" : "<code>#{match}</code>"
      end.gsub(/(?:```|<code>)(ruby|js|html|erb|css|java|shell|sh|python|php|html|objc|scss)\n(.*)(?:<\/code>|```)/m, '<code class="\1">\2</code>')
      return html_syntax_highlighter(f == 'README' ? "<pre>#{code}</pre>" : code).html_safe
    end
    nil
  end

  def html_syntax_highlighter(html)
    doc = Nokogiri::HTML(html)
    doc.search("//code").each do |code|
      next if code[:class].nil?
      # convert github code name to highlight_code's name
      lang = case code[:class].to_s
      when "objc"
        "objective-c"
      when "php"
        :js
      else
        code[:class]
      end
      code.replace highlight_code(lang, code.text.rstrip)
    end
    doc.to_s
  end

end

app/views/libraries/_summary.html.haml
- library, dependency = summary.is_a?(Library) ? [summary, nil] : [summary.source, summary]
.panel.panel-default
  .panel-heading
    .pull-right
      - if dependency
        - unless dependency.requirement.blank?
          %code= dependency.requirement
        - unless dependency.environment.blank?
          %span.label.label-info= dependency.environment
      - else
        %em= "#{pluralize number_with_delimiter(library.used_by.count), 'library'} using it"
        %span.label.label-info= library.manager
    - if @votes.include?(library.id)
      %i.fa.fa-star.text-warning
    - else
      = link_to "javascript:void(0)", onclick: "vote(this, #{library.id})" do
        %i.fa.fa-chevron-circle-up.text-success
    (#{number_with_delimiter library.votes_count})
    = link_to library.name, library_path(library.manager, library.name)
  .panel-body= library.description

app/views/libraries/graph.html.haml
- content_for :title, "#{@manager} libraries graph"

%h1 Top 100 <em>#{@manager}</em> libraries

#graph-container

:css
  .node {
    stroke: #fff;
    stroke-width: 1.5px;
  }

  .link {
    stroke: #999;
    stroke-opacity: .6;
  }

  .text {
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
  }

  .overlay {
    fill: none;
    pointer-events: all;
    cursor: move;
  }

- content_for :page_javascript do
  :javascript
    var force = d3.layout.force()
        .charge(-500)
        .linkDistance(300);

    var zoom = d3.behavior.zoom()
      .scaleExtent([0.5, 10])
      .on("zoom", zoomed);

    var svg = d3.select("#graph-container").append("svg")
        .attr("width", "100%")
        .attr("height", 500)
      .append("g")
        .attr('transform','scale(0.5)')
        .call(zoom)
      .append("g");

    var overlay = svg.append("rect")
        .attr("width", 10000)
        .attr("height", 10000)
        .attr("class", "overlay");

    d3.json("#{graph_path}.json", function(error, graph) {
      force
          .nodes(graph.nodes)
          .links(graph.links)
          .start();

      var link = svg.selectAll(".link")
          .data(graph.links)
        .enter().append("line")
          .attr("class", "link");

      var node = svg.selectAll(".node")
          .data(graph.nodes)
        .enter().append("circle")
          .attr("class", "node")
          .attr("r", 5)
          .style("fill", "red");

      var text = svg.selectAll(".text")
        .data(graph.nodes)
      .enter().append("text")
        .attr("class", "text")
        .text(function(d) { return d.name; });

      force.on("tick", function() {
        link.attr("x1", function(d) { return d.source.x; })
            .attr("y1", function(d) { return d.source.y; })
            .attr("x2", function(d) { return d.target.x; })
            .attr("y2", function(d) { return d.target.y; });

        node.attr("cx", function(d) { return d.x; })
            .attr("cy", function(d) { return d.y; });

        text.attr("x", function(d) { return d.x; })
            .attr("y", function(d) { return d.y; });
      });
    });

    function zoomed() {
      d3.selectAll('.node,.link,.text').attr("transform", "translate(" + d3.event.translate + ")scale(" + d3.event.scale + ")");
    }

app/views/libraries/index.html.haml
- content_for :title, "Popular #{@manager} libraries"

app/views/libraries/show.html.haml
- content_for :title, @library.language ? "#{@library.language} library #{@library.name}" : @library.name

%article
  .row
    .col-lg-12
      %h1
        - if @library.language
          %small.pull-right
            %span.label.label-success= @library.language
        = @library.name
        - if category = @library.predict_category
          %small (#{category})
        - if !logged_in? or !current_user.has_voted?(@library)
          = link_to "Vote", vote_path(@library), class: 'btn btn-small btn-success', method: 'POST'
        - else
          %small
            %span.label.label-warning Voted
  .row
    .col-lg-6.col-sm-8
      - if !@library.homepage_uri.blank?
        %h4= link_to @library.homepage_uri, @library.homepage_uri, class: 'green', rel: 'nofollow'
      - elsif !@library.repository_uri.blank?
        %h4= link_to @library.repository_uri, @library.repository_uri, class: 'green', rel: 'nofollow'
      %p.text-muted.h3= @library.description

      - if @library.github?
        - user, name = @library.github_repository
        .spacer20
        %h2
          %i.fa.fa-github
          Repository
          %small= link_to "#{user}/#{name}", "http://github.com/#{user}/#{name}", rel: 'nofollow'
        %iframe{src: "http://ghbtns.com/github-btn.html?user=#{user}&repo=#{name}&type=watch&count=true", allowtransparency: "true", frameborder: "0", scrolling: "0", width: "110px", height: "20px"}
        %iframe{src: "http://ghbtns.com/github-btn.html?user=#{user}&repo=#{name}&type=fork&count=true", allowtransparency: "true", frameborder: "0", scrolling: "0", width: "95px", height: "20px"}

    .col-lg-2.visible-lg.text-center
      .panel.panel-default
        .panel-heading <span class="b">#</span> votes
        .panel-body
          .text-large= number_with_delimiter @library.votes.count
    .col-lg-2.visible-lg.text-center
      .panel.panel-default
        .panel-heading <span class="b">#</span> downloads
        .panel-body
          .text-large= @library.downloads.to_i > 0 ? number_with_delimiter(@library.downloads) : 'N/A'
    .col-lg-2.visible-lg.text-center
      .panel.panel-default
        .panel-heading <span class="b">#</span> libraries using it
        .panel-body
          .text-large= number_with_delimiter @library.used_by.count

  .spacer20

- if (count = @library.users.count) > 0
  .row.hidden-xs
    .col-lg-12
      %h2
        Voters
        %a.twitter-share-button{href: "https://twitter.com/share", "data-url" => request.url, "data-via" => "depstack", 'data-text' => "Vote for #{@library.name}!"} Promote #{@library.name}
  .row.hidden-xs
    - users = @library.users.first(22)
    - users.each_with_index do |u, i|
      .col-lg-1.col-md-1.col-sm-1.voter
        = link_to "https://github.com/#{u.login}", rel: 'nofollow' do
          - if !u.avatar_url.blank?
            = image_tag u.avatar_url, alt: u.name
          .text-center= u.login
      - if (i + 1) % 12 == 0
        </div><div class="row">
    - if users.size < count
      .col-lg-2.col-md-2.col-sm-2
        .spacer30
        and #{count - users.size} others...

- if @library.requirements.count > 0
  .row
    .col-lg-12
      %h2 Popular libraries using it
  .row
    .col-lg-12
      = render partial: '/libraries/summary',  collection: @library.top_requirements(10)

- if @library.github? and @library.github_repository and false
  .row
    .col-lg-12
      %h2 Documentation
      %section.panel.panel-default#readme
        .panel-heading README
        .panel-body
          = find_and_preserve do
            = render_readme(*@library.github_repository)